arch: NestedUNet
batch_size: 4
dataset: Eye
deep_supervision: true
early_stopping: -1
epochs: 200
factor: 0.1
gamma: 0.6666666666666666
img_ext: .jpg
input_channels: 3
input_h: 224
input_w: 224
loss: BCEDiceLoss
lr: 0.001
mask_ext: .png
milestones: 1,2
min_lr: 1.0e-05
momentum: 0.9
name: Eye_NestedUNet_wDS
nesterov: false
num_classes: 1
num_workers: 0
optimizer: Adam
output_channels: 1
patience: 2
scheduler: CosineAnnealingLR
t: 2
weight_decay: 0.0001
